[clang-tidy] Vote: Type safety checks
ComputationalRadiationPhysics/contributing pull request #51
Opened 2021-05-27 10:14 UTC by j-stephan

This PR adds type safety checks to our .clang-tidy file.

* No implicit `bool`-to-pointer conversions ([Link](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-bool-pointer-implicit-conversion.html))
* No implicit `bool` conversions to any builtin type ([Link](https://clang.llvm.org/extra/clang-tidy/checks/readability-implicit-bool-conversion.html))
* Avoid precision loss on widening integer casts ([Link](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-misplaced-widening-cast.html))
* Be extra careful with `signed char` ([Link](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-signed-char-misuse.html))
* Do not embed `\0` in strings ([Link](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-string-literal-with-embedded-nul.html))
* Do not misuse non-class `enum`s ([Link](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-suspicious-enum-usage.html))
* Detect (accidentally) swapped arguments ([Link](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-swapped-arguments.html))
* Do not implement C-style variadic functions ([Link](https://clang.llvm.org/extra/clang-tidy/checks/cert-dcl50-cpp.html))
* Do not use C-style variadic arguments ([Link](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-vararg.html))
* No implicit narrowing conversions ([Link](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-narrowing-conversions.html))
* No array-to-pointer decays ([Link](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-bounds-array-to-pointer-decay.html))
* Do not use `const_cast` ([Link](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-const-cast.html))
* Do not use unsafe C-style casts ([Link](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-cstyle-cast.html))
* Do not use any C-style casts ([Link](https://clang.llvm.org/extra/clang-tidy/checks/google-readability-casting.html))
* Do not use `reinterpret_cast` ([Link](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-reinterpret-cast.html))
* Do not use `static_cast` to cast base classes to derived classes ([Link](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-static-cast-downcast.html))
* Do not access `union` members ([Link](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-union-access.html))
* Use `std::(u)intXX_t` instead of signed/unsigned `short`, `long` and `long long` ([Link](https://clang.llvm.org/extra/clang-tidy/checks/google-runtime-int.html))
* Do not perform bitwise operations on signed integers ([Link](https://clang.llvm.org/extra/clang-tidy/checks/hicpp-signed-bitwise.html))
* Use `bool` literals instead of `0` and `1` ([Link](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-bool-literals.html))
* Use `nullptr` instead of `NULL` or `0` ([Link](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html))
* Use transparent functors ([Link](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-transparent-functors.html))
* Even with `auto`, use `const`, `*` and `&` ([Link](https://clang.llvm.org/extra/clang-tidy/checks/readability-qualified-auto.html))

Voting will close on Friday, 04 June 2021, 18:00 HZDR time.

### Vote

Check | Yes | No | Comment
------|-----|----|--------
No implicit `bool`-to-pointer conversion | 1 | 0 | 
No implicit `bool` conversion to any type | 1 | 0 | 
No precision loss on widening integer casts | 1 | 0 | 
Special care for `signed char` | 1 | 0 | 
No embedded `\0` in strings | 1 | 0 | 
No `enum` misuse | 1 | 0 | 
Detect swapped arguments | 1 | 0 | 
No C-style variadic functions | 1 | 0 | 
No C-style variadic arguments | 1 | 0 | 
No implicit narrowing | 1 | 0 | 
No array-to-pointer decay | 1 | 0 | 
No `const_cast` | 1 | 0 | 
No **unsafe** C-style casts | 1 | 0 | 
No C-style casts **in any form** | 1 | 0 | 
No `reinterpret_cast` | 0 | 1 | 
No `static_cast` for downcasting | 1 | 0 | 
No access to `union` members | 1 | 0 | 
Use fixed-width integer types | 1 | 0 | 
No bitwise operations on signed integers | 1 | 0 | 
Use `bool` literals | 1 | 0 | 
Use `nullptr` | 1 | 0 | 
Use transparent functors | 1 | 0 | 
Use qualified `auto` | 1 | 0 | 

### Vote template

```
Check | Yes | No | Comment
------|-----|----|--------
No implicit `bool`-to-pointer conversion | X | X | 
No implicit `bool` conversion to any type | X | X | 
No precision loss on widening integer casts | X | X | 
Special care for `signed char` | X | X | 
No embedded `\0` in strings | X | X | 
No `enum` misuse | X | X | 
Detect swapped arguments | X | X | 
No C-style variadic functions | X | X | 
No C-style variadic arguments | X | X | 
No implicit narrowing | X | X | 
No array-to-pointer decay | X | X | 
No `const_cast` | X | X | 
No **unsafe** C-style casts | X | X | 
No C-style casts **in any form** | X | X | 
No `reinterpret_cast` | X | X | 
No `static_cast` for downcasting | X | X | 
No access to `union` members | X | X | 
Use fixed-width integer types | X | X | 
No bitwise operations on signed integers | X | X | 
Use `bool` literals | X | X | 
Use `nullptr` | X | X | 
Use transparent functors | X | X | 
Use qualified `auto` | X | X | 
```

2021-05-27 10:30 UTC, bernhardmgruber commented
Check | Yes | No | Comment
------|-----|----|--------
No implicit `bool`-to-pointer conversion | 2 | 0 | 
No implicit `bool` conversion to any type | 2 | 0 | 
No precision loss on widening integer casts | 2 | 0 | 
Special care for `signed char` | 2 | 0 | 
No embedded `\0` in strings | 1 | 1 | 
No `enum` misuse | 2 | 0 | 
Detect swapped arguments | 2 | 0 | 
No C-style variadic functions | 2 | 0 | 
No C-style variadic arguments | 2 | 0 | 
No implicit narrowing | 2 | 0 | 
No array-to-pointer decay | 2 | 0 | 
No `const_cast` | 1 | 1 | 
No **unsafe** C-style casts | 2 | 0 | 
No C-style casts **in any form** | 2 | 0 | 
No `reinterpret_cast` | 0 | 2 | 
No `static_cast` for downcasting | 2 | 0 | 
No access to `union` members | 1 | 1 | 
Use fixed-width integer types | 2 | 0 | 
No bitwise operations on signed integers | 2 | 0 | 
Use `bool` literals | 2 | 0 | 
Use `nullptr` | 2 | 0 | 
Use transparent functors | 2 | 0 | 
Use qualified `auto` | 1 | 1 |

2021-05-27 10:44 UTC, psychocoderHPC commented
Check | Yes | No | Comment
------|-----|----|--------
No implicit `bool`-to-pointer conversion | 3 | 0 | 
No implicit `bool` conversion to any type | 3 | 0 | 
No precision loss on widening integer casts | 3 | 0 | 
Special care for `signed char` | 3 | 0 | 
No embedded `\0` in strings | 1 | 2 | 
No `enum` misuse | 3 | 0 | 
Detect swapped arguments | 3 | 0 | 
No C-style variadic functions | 3 | 0 | 
No C-style variadic arguments | 3 | 0 | 
No implicit narrowing | 3 | 0 | 
No array-to-pointer decay | 3 | 0 | 
No `const_cast` | 1 | 2 | 
No **unsafe** C-style casts | 3 | 0 | 
No C-style casts **in any form** | 3 | 0 | 
No `reinterpret_cast` | 0 | 3 | 
No `static_cast` for downcasting | 3 | 0 | 
No access to `union` members | 1 | 2 | 
Use fixed-width integer types | 2 | 1 | For some code parts it is not possible to use fixed with integers because you do not know the mapped native type. Type traits should also be specialized with native types because e.g `size_t` and `uint32_t` can be mapped to the same type, in this case, you will specialize the trait twice with the same type.
No bitwise operations on signed integers | 2 | 1 |  `0 >> 2` can be used to move `1` from the left side into the value.
Use `bool` literals | 3 | 0 | 
Use `nullptr` | 3 | 0 | 
Use transparent functors | 3 | 0 | 
Use qualified `auto` | 2 | 1 |

2021-06-01 12:21 UTC, SimeonEhrig commented
Check | Yes | No | Comment
-- | -- | -- | --
No implicit bool-to-pointer conversion | 4 | 0 | &nbsp;
No implicit bool conversion to any type | 4 | 0 | &nbsp;
No precision loss on widening integer casts | 4 | 0 | &nbsp;
Special care for signed char | 4 | 0 | &nbsp;
No embedded \0 in strings | 1 | 2 | &nbsp;
No enum misuse | 4 | 0 | &nbsp;
Detect swapped arguments | 4 | 0 | &nbsp;
No C-style variadic functions | 4 | 0 | &nbsp;
No C-style variadic arguments | 4 | 0 | &nbsp;
No implicit narrowing | 4| 0 | &nbsp;
No array-to-pointer decay | 4 | 0 | &nbsp;
No const_cast | 1 | 2 | &nbsp;
No unsafe C-style casts | 4 | 0 | &nbsp;
No C-style casts in any form | 4 | 0 | &nbsp;
No reinterpret_cast | 0 | 4 | &nbsp; 
No static_cast for downcasting | 4 | 0 | &nbsp;
No access to union members | 1 | 2 | &nbsp;
Use fixed-width integer types | 2 | 2 | 
No bitwise operations on signed integers | 2 | 1 | 
Use bool literals | 4 | 0 | &nbsp;
Use nullptr | 4 | 0 | &nbsp;
Use transparent functors | 3 | 0 | &nbsp;
Use qualified auto | 3 | 1 | I prefer more explicit types (but `auto` is not bad in general ;-) )

2021-06-04 08:41 UTC, j-stephan commented
Changing my vote:

Check | Yes | No | Comment
------|-----|----|--------
No implicit `bool`-to-pointer conversion | 4 | 0 | 
No implicit `bool` conversion to any type | 4 | 0 | 
No precision loss on widening integer casts | 4 | 0 | 
Special care for `signed char` | 4 | 0 | 
No embedded `\0` in strings | 1 | 2 | 
No `enum` misuse | 4 | 0 | 
Detect swapped arguments | 4 | 0 | 
No C-style variadic functions | 4 | 0 | 
No C-style variadic arguments | 4 | 0 | 
No implicit narrowing | 4 | 0 | 
No array-to-pointer decay | 4 | 0 | 
No `const_cast` | 1 | 2 | 
No **unsafe** C-style casts | 4 | 0 | 
No C-style casts **in any form** | 4 | 0 | 
No `reinterpret_cast` | 0 | 4 | 
No `static_cast` for downcasting | 4 | 0 | 
No access to `union` members | 1 | 2 | 
Use fixed-width integer types | 1 | 3 | Changed 
No bitwise operations on signed integers | 2 | 1 | 
Use `bool` literals | 4 | 0 | 
Use `nullptr` | 4 | 0 | 
Use transparent functors | 3 | 0 | 
Use qualified `auto` | 3 | 1 |

2021-06-07 08:39 UTC, bernhardmgruber requested changes

2021-06-07 08:39 UTC, bernhardmgruber commented on formatting-tools/.clang-tidy
> +  - { key: bugprone-signed-char-misuse.CharTypedefsToIgnore, value: int8_t,std::int8_t}
```suggestion
  - { key: bugprone-signed-char-misuse.CharTypedefsToIgnore, value: "int8_t,std::int8_t"}
```

2021-06-07 08:39 UTC, bernhardmgruber commented on formatting-tools/.clang-tidy
> +  - { key: bugprone-suspicious-enum-usage.StrictMode: 1}
```suggestion
  - { key: bugprone-suspicious-enum-usage.StrictMode, value: 1}
```

2021-06-07 08:42 UTC, bernhardmgruber approved these changes

2021-06-15 12:06 UTC, merged